http monitor handles excluded headers
signalfx/signalfx-agent pull request #1524
Opened 2020-11-06 19:47 UTC by xp-1000

hello,
to make it possible to change host header.

2020-11-09 19:28 UTC, keitwb requested changes
The code changes seem fine.  Mainly just a few minor grammatical issues to make it more idiomatic English.

2020-11-09 19:28 UTC, keitwb commented on pkg/monitors/http/metadata.yaml
> +      usefull to override the `host` header.
```suggestion
      useful to override the `host` header.
```

2020-11-09 19:28 UTC, keitwb commented on pkg/monitors/http/metadata.yaml
> +      The form of this body will often depends on the `Content-Type` header.
```suggestion
      The form of this body will often depend on the `Content-Type` header.
```

2020-11-09 19:28 UTC, keitwb commented on pkg/monitors/http/metadata.yaml
> +      * By default, it will follow redirect. Possible to disable it using
```suggestion
      * By default, it will follow redirects. It is possible to disable that behavior using 
```

2020-11-09 19:28 UTC, keitwb commented on pkg/monitors/http/metadata.yaml
> +    Some configuration options could change the resulted values:
```suggestion
    Some configuration options change the resulting values:
```

2020-11-09 19:28 UTC, keitwb commented on pkg/monitors/http/metadata.yaml
> +    To create a webcheck from URL, you need to split it into different
```suggestion
    To create a webcheck from a URL, you need to split it into different 
```

2020-11-09 19:28 UTC, keitwb commented on pkg/monitors/http/metadata.yaml
> +      eventually the `GET` method parameters with `?` separator.
```suggestion
      finally the `GET` method parameters with `?` separator.
```

2020-11-09 19:28 UTC, keitwb commented on pkg/monitors/http/metadata.yaml
> +    implicit and make the behavior similar to what `curl` does.
```suggestion
    it is implicit and makes the behavior similar to what `curl` does.
```

2020-11-09 19:28 UTC, keitwb commented on pkg/monitors/http/metadata.yaml
> +      By default equals to `200` it could be useful to change it if you
```suggestion
      By default it is `200` it could be useful to change it if you 
```

2020-11-09 19:28 UTC, keitwb commented on pkg/monitors/http/metadata.yaml
> +    * `curl -I http://signalfx.com` (`http.status_code=301` because does not
```suggestion
    * `curl -I http://signalfx.com` (`http.status_code=301` because it does not 
```

2020-11-10 11:05 UTC, xp-1000 commented
> The code changes seem fine. Mainly just a few minor grammatical issues to make it more idiomatic English.

Thanks @keitwb I am sorry for that, my english is far too be good.

2020-11-10 18:55 UTC, keitwb approved these changes

2020-11-10 18:55 UTC, merged