Update tracker.go to add pod name as a tag
signalfx/signalfx-agent pull request #1557
Opened 2020-12-16 00:31 UTC by harnitsignalfx

It is valuable to the customers to track the pod name in the span tag. Did some testing and confirmed that this worked as the kubernetes_pod_name seems to be available in the map of dims that the agent checks against (dims: map[container_id,container_image,container_name,container_spec_name:,kubernetes_namespace, kubernetes_pod_name, kubernetes_pod_uid]
Though there may be other implications that I'm not aware of (the MTS with these dimensions also get updated with properties?)

2020-12-17 14:24 UTC, keitwb commented
It's the _other implications_ that I'm a bit wary of.  @jrcamp since you've dealt with this stuff recently can you think of the implications of this?

2020-12-17 15:29 UTC, jrcamp requested changes
This field is currently used in 2 different ways. One is to enrich spans (what you're trying to do it seems) and the other is for correlation. We don't want the dimensions we correlate against to change so this will need some minor refactoring so correlation uses the existing list and a new list can be made for span enrichment.

2020-12-17 17:36 UTC, harnitsignalfx commented
Ack, I'll try to propose that change! Thank you both!

2020-12-18 01:15 UTC, harnitsignalfx commented
Closing in lieu of https://github.com/signalfx/signalfx-agent/pull/1559

2020-12-18 01:15 UTC, closed without merging