Add support to URL Query
signalfx/signalfx-agent pull request #1558
Opened 2020-12-17 18:53 UTC by dloucasfx

If path includes a query, then the `normalizeURL` unwillingly strips the query part
example:
with this config, the monitor ends up hitting the endpoint `/Tools-and-Home-Improvement/b/` instead the full path
```
  - type: http
    host: amazon.com
    useHTTPS: true
    path: '/Tools-and-Home-Improvement/b/?ie=UTF8&node=228013&ref_=nav_cs_hi'
    method: GET
```
Signed-off-by: Dani Louca <dlouca@splunk.com>

2020-12-17 19:00 UTC, keitwb requested changes
Do the same thing at https://github.com/signalfx/signalfx-agent/blob/9a7160accab22b51c11756177259f5fedf75dc90/pkg/monitors/http/http.go#L142

2020-12-17 19:01 UTC, keitwb commented
Also @xp-1000,  heads up in case you have any  input on this.

2020-12-17 19:54 UTC, dloucasfx commented
> Do the same thing at
> 
> https://github.com/signalfx/signalfx-agent/blob/9a7160accab22b51c11756177259f5fedf75dc90/pkg/monitors/http/http.go#L142

done

2020-12-17 20:40 UTC, keitwb approved these changes

2020-12-18 18:34 UTC, merged

2020-12-21 14:59 UTC, xp-1000 commented
> Also @xp-1000, heads up in case you have any input on this.

thanks for the ping and the improvement, it seems good for me.