Support postgresql 13
signalfx/signalfx-agent pull request #1607
Opened 2021-02-16 19:40 UTC by rmfitzpatrick

These changes add support for Postgres 13, whose pg_stat_statements extension provided a breaking column name change of `total_time` -> `total_exec_time` to distinguish it from the added, optional `total_plan_time`.  This is done by querying the view's columns for the configured master db and rendering the queries before the underlying SQL monitor Configure().

2021-02-16 19:51 UTC, keitwb requested changes
The procedure that determines the column name needs to be resilient against the DB being down when the agent first starts up.

2021-02-16 22:18 UTC, rmfitzpatrick commented
> The procedure that determines the column name needs to be resilient against the DB being down when the agent first starts up.

@keitwb I've shifted the sql monitor creation to the main postgres monitor loop to allow retries.  This better?

2021-02-18 15:04 UTC, keitwb approved these changes
Yes, make sure the integration test is actually checking for the metric in question and it is good to go.

2021-02-18 15:58 UTC, rmfitzpatrick commented
> Yes, make sure the integration test is actually checking for the metric in question and it is good to go.

I've verified the added 13-alpine run fails without these changes.

2021-02-18 15:58 UTC, merged