Add Helm 3+ as the supported version for K8s
signalfx/signalfx-agent pull request #1892
Opened 2021-09-01 21:12 UTC by tmorrisonsfx

Add Helm 3+ as the supported version for K8s. This relates to https://github.com/signalfx/signalfx-agent/pull/1891 and https://signalfuse.atlassian.net/browse/DOCS-2570.

2021-09-01 21:27 UTC, tmorrisonsfx commented
> @tmorrisonsfx Should https://github.com/signalfx/signalfx-agent/blob/main/docs/agent-k8s-install-helm.md also be updated for helm v3+ support and the `--generate-name` option?

Yes, I missed that one. Will add that now. Thanks!

2021-09-02 14:46 UTC, tmorrisonsfx commented
@jcheng-splunk PTAL at the changes for https://github.com/signalfx/signalfx-agent/blob/main/docs/agent-k8s-install-helm.md. Thanks!

2021-09-02 14:53 UTC, jcheng-splunk commented on docs/agent-k8s-install-helm.md
> +  - The installation chart for the Smart Agent is compatible with Helm version 2 or Helm version 3. Helm version 2 is [deprecated](https://helm.sh/blog/helm-v2-deprecation-timeline/). To learn more,
```suggestion
  - The installation chart for the Smart Agent is compatible with Helm version 3. Helm version 2 is [deprecated](https://helm.sh/blog/helm-v2-deprecation-timeline/). To learn more, see the [Helm site](https://helm.sh/).
```

2021-09-02 14:59 UTC, jcheng-splunk commented on docs/agent-k8s-install-helm.md
> +  - The installation chart for the Smart Agent is compatible with Helm version 2 or Helm version 3. Helm version 2 is [deprecated](https://helm.sh/blog/helm-v2-deprecation-timeline/). To learn more,
@tmorrisonsfx If we're including the `--generate-name` option in the install commands, we should drop Helm v2 compatibility.

2021-09-03 08:40 UTC, theletterf requested changes
Nit: 3+ should be `3 or higher` (we don't use `+` notation in our docs).

2021-09-03 08:40 UTC, theletterf commented on README.md
> +for more information. Helm 3+ is the supported version.
```suggestion
See our [Kubernetes setup instructions](./docs/kubernetes-setup.md) and [Monitor
Kubernetes](https://docs.splunk.com/Observability/infrastructure/navigators/k8s.html)
for more information. Helm version 3 or higher is supported.
```

2021-09-03 08:40 UTC, theletterf commented on docs/agent-k8s-install-helm.md
> +     The ``--generate-name`` option is only supported for Helm version 3+.
```suggestion
     The ``--generate-name`` option is only supported for Helm version 3 or higher.
```

2021-09-03 14:37 UTC, theletterf approved these changes

2021-09-03 15:09 UTC, tmorrisonsfx commented
@jcheng-splunk Hi, Jeff. Do you know anything about the build failures? One of them is required to pass before I can merge this PR. Thanks!

2021-09-03 15:14 UTC, jcheng-splunk commented
> @jcheng-splunk Hi, Jeff. Do you know anything about the build failures? One of them is required to pass before I can merge this PR. Thanks!

The failures are unrelated.  We can merge whenever you're ready.

2021-09-03 15:15 UTC, tmorrisonsfx commented
> > @jcheng-splunk Hi, Jeff. Do you know anything about the build failures? One of them is required to pass before I can merge this PR. Thanks!
> 
> The failures are unrelated. We can merge whenever you're ready.

Ok, this is ready to merge, but I don't have the option. Thanks.

2021-09-03 15:25 UTC, merged